name: Compile Tasmota AWS IoT firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest Tasmota release
        id: get_current_release
        run: |
          CURRENT_RELEASE_TAG=$(curl -s https://api.github.com/repos/arendst/Tasmota/releases/latest | jq -r '.tag_name')
          echo "current_release_tag=$CURRENT_RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Current Tasmota release: $CURRENT_RELEASE_TAG"

      - name: Checkout latest Tasmota release
        uses: actions/checkout@v4
        with:
          repository: arendst/tasmota
          ref: refs/tags/${{ steps.get_current_release.outputs.current_release_tag }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install wheel
          pip install -U platformio

      - name: Run PlatformIO
        env:
          PLATFORMIO_BUILD_FLAGS: -DUSE_MQTT_TLS -DUSE_MQTT_AWS_IOT_LIGHT -DUSE_MQTT_TLS_CA_CERT
        run: |
          platformio run -e tasmota -v

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: ./build_output

      - name: Unzip firmware artifacts
        run: |
          7z x firmware.zip
          mv firmware/tasmota.bin firmware/tasmota-aws-iot.bin
          mv firmware/tasmota.bin.gz firmware/tasmota-aws-iot.bin.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_current_release.outputs.current_release_tag }}
          files: ./firmware/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store Tasmota version
        run: |
          echo "${{ steps.get_current_release.outputs.current_release_tag }}" > previous_tasmota_release.txt

      - name: Upload Tasmota version
        uses: actions/upload-artifact@v4
        with:
          name: previous_tasmota_release.txt
          path: previous_tasmota_release.txt
